- name: Setup Flask App Locally
  hosts: localhost
  become: true
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Python3, pip
      apt:
        name: [python3, python3-pip]
        state: present

    - name: Install Flask and psutil
      pip:
        name: [flask, psutil]

    - name: Start Flask App
      shell: python3 app/app.py
      async: 30
      poll: 0
